name: helics-environment
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pip
  - jupyter
  - pip:
      - OpenDSSDirect.py==0.7.0
      - pypower
      - helics==3.5
      - jupyterlab
