name: helics-environment
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pip
  - pip:
      - OpenDSSDirect.py
      - pypower
      - helics
